Models/EF/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WasteFoodDistributionSystem.Models.EF
{
    public class Restaurant
    {
        [Key]
        public int RestaurantId { get; set; }

        [Required, MaxLength(255)]
        public string Name { get; set; }

        [Required, MaxLength(255)]
        public string Address { get; set; }

        [Required, MaxLength(50)]
        public string ContactNumber { get; set; }

        [Required, MaxLength(255), EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [StringLength(255, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters long")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+])(?!.*\s).*$", ErrorMessage = "Password must contain at least one uppercase letter, one lowercase letter, one numeric digit, and one special character")]
        public string Password { get; set; }
        public string Image { get; set; }
    }
}

Controllers/RestaurantController.cs
using System.Linq;
using System.Web.Mvc;
using WasteFoodDistributionSystem.Auth;
using WasteFoodDistributionSystem.Models.EF;
using WasteFoodDistributionSystem.Models.ViewModel;
using WasteFoodDistributionSystem.Models;
using WasteFoodDistributionSystem.Service;
using System;

namespace WasteFoodDistributionSystem.Controllers
{
    [ValidDonor]
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index(int? page)
        {
            const int pageSize = 8;
            var restaurantId = (Session["user"] as Restaurant).RestaurantId;
            using (var dbContext = new FoodDistributionDbContext())
            {
                var requests = dbContext.CollectRequests
                                    .Where(r => r.RestaurantId == restaurantId && r.Status != "Complete")
                                    .OrderByDescending(r => r.RequestId)
                                    .Skip((page.GetValueOrDefault(1) - 1) * pageSize)
                                    .Take(pageSize)
                                    .ToList();
                var count = dbContext.CollectRequests
                                .Where(r => r.RestaurantId == restaurantId && r.Status != "Complete")
                                .Count();
                ViewBag.CurrentPage = page.GetValueOrDefault(1);
                ViewBag.TotalPages = (int)Math.Ceiling(count / (double)pageSize);
                return View(requests);
            }
        }


        public ActionResult History(int? page)
        {
            const int pageSize = 8;
            var restaurantId = (Session["user"] as Restaurant).RestaurantId;
            var dbContext = new FoodDistributionDbContext();
            var requests = dbContext.FoodDistributions
                                .Where(r => r.CollectRequest.RestaurantId == restaurantId && r.CollectRequest.Status == "Complete")
                                .OrderByDescending(r => r.CollectRequest.RequestId)
                                .Skip((page.GetValueOrDefault(1) - 1) * pageSize)
                                .Take(pageSize)
                                .ToList();
            var count = dbContext.FoodDistributions
                            .Where(r => r.CollectRequest.RestaurantId == restaurantId && r.CollectRequest.Status == "Complete")
                            .Count();
            ViewBag.CurrentPage = page.GetValueOrDefault(1);
            ViewBag.TotalPages = (int)Math.Ceiling(count / (double)pageSize);

            //Chart Data
            var dontaion = dbContext.CollectRequests.Where(r => r.RestaurantId == restaurantId && r.Status == "Complete").ToList();
            ViewBag.Data = dontaion.Select(d => new { Date = d.CreatedAt.ToString("ddd hh:mm tt"), d.Amount }).ToArray();

            return View(requests);
        }

        public ActionResult DonorProfile() => View(Session["user"] as Restaurant);
        public ActionResult Setting()
        {
            var restaurant = Session["user"] as Restaurant;
            var model = new RestaurantSettingModel
            {
                RestaurantId = restaurant.RestaurantId,
                Name = restaurant.Name,
                Email = restaurant.Email,
                Password = restaurant.Password,
                ContactNumber = restaurant.ContactNumber,
                Address = restaurant.Address,
                Image = restaurant.Image,
            };
            return View(model);
        }

        public ActionResult AddDonation() => View();
        public ActionResult DonationDetails(int id) => View(new FoodDistributionDbContext().FoodDistributions.Where(x => x.CollectRequest.RequestId == id).FirstOrDefault());
        public ActionResult EditDonation(int id)
        {
            var dbContext = new FoodDistributionDbContext();
            var request = dbContext.CollectRequests.Find(id);
            var model = new DonationModel
            {
                Name = request.Name,
                Amount = request.Amount,
                PreservTime = request.MaximumPreservationTime,
                OldImgUrl = request.Image
            };
            ViewBag.Id = id;
            return View(model);
        }
        public ActionResult DistributerProfile(int id)
        {
            var dbContext = new FoodDistributionDbContext();
            var emp = dbContext.Employees.Find(id);
            var dispatches = dbContext.CollectRequests.Where(d => d.EmployeeId == id && d.Status == "Complete").ToList();
            ViewBag.Dispatches = dispatches.Count();
            return View(emp);
        }



        [AllowAnonymous]
        [PreventAuthenticatedAccess]
        public ActionResult Registration() => View();

        [AllowAnonymous]
        [PreventAuthenticatedAccess]
        [HttpPost]
        public ActionResult Registration(Restaurant restaurant)
        {
            //check if the model is valid or not
            if (!ModelState.IsValid) return View(restaurant);
            if (restaurant.Password != Request.Form["Password_Confirmation"])
            {
                ModelState.AddModelError("Password", "Password does not match");
                return View(restaurant);
            }
            using (var db = new FoodDistributionDbContext())
            {
                var user = db.Restaurants.FirstOrDefault(e => e.Email == restaurant.Email);
                if (user != null)
                {
                    ModelState.AddModelError("Email", "Email already exists");
                    return View(restaurant);
                }
            }
            var profilePiture = Request.Files["ProfilePicture"];
            if (profilePiture != null)
            {
                var ImgUrl = DefaultService.UploadImage(restaurant.Name, profilePiture, null, Server.MapPath("~/Images/RestaurentPicture/"));
                restaurant.Image = ImgUrl;
            }
            //save the employee in the database
            using (var db = new FoodDistributionDbContext())
            {
                db.Restaurants.Add(restaurant);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Setting(RestaurantSettingModel restaurant)
        {
            if (!ModelState.IsValid) return View(restaurant);
            if ((Session["user"] as Restaurant).Email != restaurant.Email)
            {
                using (var db = new FoodDistributionDbContext())
                {
                    var user = db.Restaurants.FirstOrDefault(e => e.Email == restaurant.Email);
                    if (user != null)
                    {
                        ModelState.AddModelError("Email", "Email already exists");
                        return View(restaurant);
                    }
                }
            }
            if (!string.IsNullOrEmpty(restaurant.NewPassword))
            {
                using (var db = new FoodDistributionDbContext())
                {
                    var user = db.Restaurants.FirstOrDefault(e => e.Email == restaurant.Email && e.Password == restaurant.Password);
                    if (user == null)
                    {
                        ModelState.AddModelError("Password", "Invalid password");
                        return View(restaurant);
                    }
                }
                restaurant.Password = restaurant.NewPassword;
            }
            else
            {
                restaurant.Password = (Session["user"] as Restaurant).Password;
            }
            var profilePiture = restaurant.ImageFile;
            var ImgUrl = restaurant.Image;
            if (profilePiture != null)
            {
                ImgUrl = DefaultService.UploadImage(restaurant.Name, profilePiture, restaurant.Image, Server.MapPath("~/Images/RestaurentPicture/"));
                restaurant.Image = ImgUrl;
            }
            //save the employee in the database
            using (var db = new FoodDistributionDbContext())
            {
                var user = db.Restaurants.Find(restaurant.RestaurantId);
                user.Name = restaurant.Name;
                user.Email = restaurant.Email;
                user.Password = restaurant.Password;
                user.Address = restaurant.Address;
                user.ContactNumber = restaurant.ContactNumber;
                user.Image = restaurant.Image;
                db.SaveChanges();
                Session["user"] = user;
                Session["Name"] = restaurant.Name;
            }
            return RedirectToAction("DonorProfile");
        }
        [HttpPost]
        public ActionResult AddDonation(DonationModel model)
        {
            //check if model is valid 
            if (!ModelState.IsValid) return View(model);
            var fileName = "Default.jpg";
            if (model.FoodPicture != null)
                fileName = DefaultService.UploadImage(model.Name, model.FoodPicture, model.OldImgUrl, Server.MapPath("~/Images/DonationFood/"));

            using (var db = new FoodDistributionDbContext())
            {
                var newRequest = new CollectRequest
                {
                    Name = model.Name,
                    Amount = model.Amount,
                    Image = fileName,
                    CreatedAt = DateTime.Now,
                    MaximumPreservationTime = model.PreservTime,
                    Status = "Pending",
                    RestaurantId = (Session["user"] as Restaurant).RestaurantId
                };
                db.CollectRequests.Add(newRequest);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult EditDonation(DonationModel model, int id)
        {
            //check if model is valid 
            if (!ModelState.IsValid) return View(model);

Views/Restaurant/AddDonation.cshtml
@model WasteFoodDistributionSystem.Models.ViewModel.DonationModel

@{
    ViewBag.Title = "AddDonation";
    Layout = "~/Views/Shared/_Layout_Dnr.cshtml";
}
@using (Html.BeginForm("AddDonation", "Restaurant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add Donation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-10">
            <label class="control-label">Food Picture</label>
            <input class="form-control" type="file" name="FoodPicture" />
            @Html.ValidationMessageFor(model => model.FoodPicture, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-10">
            <label for="myTimeInput">Select a time:</label>
            <input type="time" id="myTimeInput" name="PreservTime" class="form-control" step="60" value="00:00" />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="my-3 btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Restaurant/DonationDetails.cshtml
@model WasteFoodDistributionSystem.Models.EF.FoodDistribution

@{
    ViewBag.Title = "Complete";
    Layout = "~/Views/Shared/_Layout_Dnr.cshtml";
    var imageUrl = Model.CollectRequest.Image;
    imageUrl = imageUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? imageUrl : @Url.Content("~/Images/DonationFood/" + @Model.CollectRequest.Image);

}

<div>
    <img class="p-5" src="@imageUrl" alt="food_Picture" width="300" />
    <hr />
    <div class="ms-5">
        <label>Name:</label>
        <label>@Model.CollectRequest.Name</label>
    </div>
    <hr />
    <div class="ms-5">
        <label>Distributed By:</label>
        <a class="text-decoration-none" href="/Restaurant/DistributerProfile/@Model.CollectRequest.EmployeeId">@Model.CollectRequest.Employee.Name</a>
    </div>
    <hr />
    <div class="ms-5">
        <label>Amount:</label>
        <label>@Model.CollectRequest.Amount</label>
    </div>
    <hr />
    <div class="ms-5">
        <label>Create At:</label>
        <label>@Model.CollectRequest.CreatedAt</label>
    </div>
    <hr />
    <div class="ms-5">
        <label>Distributed At:</label>
        <label>@Model.DistributedAt </label>
    </div>
    <hr />
    <div class="ms-5">
        <label>Toatl Recipient(s):</label>
        <label>@Model.RecipientCount</label>
    </div>
    <hr />
    <a class="link-info mt-5" href="/Employee/Index">Back</a>
</div>

Views/Restaurant/DonorProfile.cshtml
@model WasteFoodDistributionSystem.Models.EF.Restaurant
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout_Dnr.cshtml";

    var imageUrl = Model.Image;
    imageUrl = imageUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? imageUrl : @Url.Content("~/Images/RestaurentPicture/" + Model.Image);
}

<div class="container">
    <div class="main-body">
        <div class="row flex-column align-items-center">
            <div class="col-md-4 mb-3">
                <div class="card" style="width:300px">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center justify-content-center">
                            <img src="@imageUrl" alt="Admin" class="rounded" width="280">
                            <div class="mt-3">
                                <h4>@Model.Name</h4>
                                <p class="text-secondary mb-1">Donor</p>
                                <p class="text-muted font-size-sm">@Model.Address</p>
                            </div>
                        </div>
                    </div>
                </div>
                @**Profile INFO*@
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Restaurant Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Model.Name
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Model.Email
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Phone</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Model.ContactNumber
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @Model.Address
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-12">
                                <a class="btn btn-info " href="@Url.Action("Setting", "Restaurant")">Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Restaurant/EditDonation.cshtml
@model WasteFoodDistributionSystem.Models.ViewModel.DonationModel

@{
    ViewBag.Title = "EditDonation";
    Layout = "~/Views/Shared/_Layout_Dnr.cshtml";

    var imageUrl = Model.OldImgUrl;
    imageUrl = imageUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? imageUrl : @Url.Content("~/Images/DonationFood/" + @Model.OldImgUrl);
}
@using (Html.BeginForm("EditDonation", "Restaurant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Edit Donation</h2>
        <h6>#@ViewBag.Id</h6>
        <hr />
        <img src="@imageUrl" alt="food_image" width="250" />
        @Html.HiddenFor(model => model.OldImgUrl)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group col-md-10">
            <label class="control-label">Food Picture</label>
            <input class="form-control" type="file" name="FoodPicture" />
            @Html.ValidationMessageFor(model => model.FoodPicture, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="form-group col-md-10">
                <label for="myTimeInput">Select a time:</label>
                <input type="time" id="myTimeInput" name="PreservTime" class="form-control" step="60" value="@Model.PreservTime.ToString("HH:mm")" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class=" my-3 btn btn-outline-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Restaurant/Registration.cshtml
@model WasteFoodDistributionSystem.Models.EF.Restaurant

@{
    ViewBag.Title = "Registration";
}

<section class="mx-5">
    <div class="d-flex justify-content-between">
        @using (Html.BeginForm("Registration", "Restaurant", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class=" m-auto p-5 border mt-2">
                <h1>Register</h1>
                <p class="text-muted">Join us in the fight against hunger - donate your surplus food today and make a difference!</p>
                <div class="form-group">
                    <label>Restaurant Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label>Confirm Password</label>
                    <div class="col-md-10">
                        <input class="form-control" type="password" name="Password_Confirmation" />
                    </div>
                </div>
                <div class="form-group col-10">
                    <label class="control-label">Restaurant Picture</label>
                    <input class="form-control" type="file" name="ProfilePicture" />
                </div>

                <div class="form-group mb-4">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Join" class="btn btn-outline-primary mt-3" />
                    </div>
                </div>
                <a class="link-primary text-decoration-none" href="/Home/Login">Already A Donor?</a>
            </div>
        }
        <div>
            <img src="https://thumbs.dreamstime.com/b/reduce-food-waste-cartoon-vector-illustration-good-print-postcard-environmental-warning-sticker-129373112.jpg" alt="Poster" height="600" />
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Restaurant/Setting.cshtml
@model WasteFoodDistributionSystem.Models.ViewModel.RestaurantSettingModel
@{
    ViewBag.Title = "Setting";
    Layout = "~/Views/Shared/_Layout_Dnr.cshtml";

    var imageUrl = Model.Image;
    imageUrl = imageUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? imageUrl : @Url.Content("~/Images/RestaurentPicture/" + Model.Image);
}

<div class="container">
    @using (Html.BeginForm("Setting", "Restaurant", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.RestaurantId)
        @Html.HiddenFor(model => model.Image)
        <div class="main-body">
            <div class="row flex-column align-items-center">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center justify-content-center">
                                <img src="@imageUrl" alt="Restaurant" class="rounded" width="200">
                                <div class="mt-3">
                                    <input class="form-control" type="file" name="ImageFile" />
                                </div>
                            </div>
                        </div>
                    </div>
                    @**Profile INFO*@
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Full Name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Phone</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Address</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Passowrd</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    <span class="text-muted d-block" style="font-size:12px">Leave Blank if you don't want to change</span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Change Password</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                                    <span class="text-muted d-block" style="font-size:12px">Leave Blank if you don't want to change</span>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="submit" value="Update" class="btn btn-outline-primary mt-3" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>